# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: baratron

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Install dependencies
        run: |
          uv sync --all-extras
      - name: Lint with ruff
        run: uv run ruff check .
      - name: Type check with mypy
        run: uv run mypy .
      - name: Type check with pyright
        run: uv run pyright
      - name: Test with pytest
        run: uv run pytest

permissions:
  contents: read
